//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DormFinJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ID_Receipt { get; set; }
        public Nullable<int> TenartReceipt { get; set; }
        public Nullable<decimal> PayLiving { get; set; }
        public Nullable<decimal> PayAddService { get; set; }
        public Nullable<System.DateTime> DataPay { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
